### ISSUE TITLE
Allow specifying custom compiler flags

### ISSUE THREAD

**Issue by RayCarrot** [mateusfavarin/psx-modding-toolchain#5]
As the title suggests I would like to request to allow you to specify custom compiler flags in the `config.json` file. This would be useful in my project where I need the `-fshort-enums` flag.

**Comment by mateusfavarin** [comment]
Implemented in the commit [a4c0edd](https://github.com/mateusfavarin/psx-modding-toolchain/commit/a4c0edda94d268ab73f55cccb76d20e072fd6fb6)
